# Generated by Django 6.0.6 on 2026-07-08 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_format_matricule_company_prefixe_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('recurrent', models.BooleanField(default=False, help_text='If checked, the holiday will be considered as a recurrent holiday and will be applied to all future years.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='unique_holiday_date_per_company')],
            },
        ),
    ]
