# Generated by Django 6.0.6 on 2026-07-09 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0005_alter_employee_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('en_conge', 'En Congé'), ('jour_ferie', 'Jour Férié')], default='present', max_length=20)),
                ('methode_pointage', models.CharField(choices=[('manual', 'Manual'), ('biometric', 'Biometric'), ('qr', 'QR Code')], default='manual', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_per_employee_per_date')],
            },
        ),
    ]
