# Generated by Django 6.0.6 on 2026-07-09 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_format_matricule_company_prefixe_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_effet', models.DateField(help_text="Date à partir de laquelle ces taux s'appliquent")),
                ('taux_cnss_salarial', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('taux_cnss_patronal', models.DecimalField(decimal_places=2, default=17.5, max_digits=5)),
                ('taux_inam_salarial', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('taux_inam_patronal', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('abattement_forfaitaire_pourcentage', models.DecimalField(decimal_places=2, default=28.0, max_digits=5)),
                ('plafond_abattement', models.DecimalField(decimal_places=2, default=10000000.0, max_digits=12)),
                ('montant_charge_famille', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('max_personnes_charges', models.PositiveIntegerField(default=6)),
                ('smig', models.DecimalField(decimal_places=2, default=52500, help_text='Salaire minimum interprofessionnel garanti en vigueur.', max_digits=10)),
                ('plafond_cotisation_cnss', models.DecimalField(blank=True, decimal_places=2, help_text="Laisser vide si aucun plafond ne s'applique.", max_digits=12, null=True)),
                ('jours_travail_par_mois', models.PositiveIntegerField(default=26)),
                ('bareme_irpp', models.JSONField(default=list, help_text="Liste des tranches: [{'min': 0, 'max': 900000, 'taux': 0}, ...]")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'date_effet'), name='unique_payroll_setting_per_company_per_date')],
            },
        ),
    ]
