# Generated by Django 6.0.6 on 2026-07-09 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_matricule'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollsetting',
            old_name='taux_cnss_patronal',
            new_name='taux_cnss_patronale',
        ),
        migrations.RenameField(
            model_name='payrollsetting',
            old_name='taux_cnss_salarial',
            new_name='taux_cnss_salariale',
        ),
        migrations.RenameField(
            model_name='payrollsetting',
            old_name='taux_inam_patronal',
            new_name='taux_inam_patronale',
        ),
        migrations.RenameField(
            model_name='payrollsetting',
            old_name='taux_inam_salarial',
            new_name='taux_inam_salariale',
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mois', models.PositiveIntegerField(help_text='Mois de la fiche de paie (1-12)')),
                ('annee', models.PositiveIntegerField()),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jours_absence_non_payee', models.PositiveIntegerField(default=0)),
                ('cotisation_cnss_salariale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotisation_inam_salariale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotisation_cnss_patronale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotisation_inam_patronale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenu_imposable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_personnes_charges', models.PositiveIntegerField(default=0)),
                ('charges_famille_deduites', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('irpp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('paye', 'Payé')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'mois', 'annee'), name='unique_payslip_per_employee_per_month')],
            },
        ),
    ]
