# Generated by Django 6.0.6 on 2026-07-10 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_format_matricule_company_prefixe_matricule'),
        ('payroll', '0002_rename_taux_cnss_patronal_payrollsetting_taux_cnss_patronale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('type_composant', models.CharField(choices=[('gain', 'Gain (ajouté au brut)'), ('retenue', 'Retenue (déduite du net)')], max_length=20)),
                ('imposable', models.BooleanField(default=True, help_text="Ce composant est-il soumis à l'IRPP?")),
                ('soumis_cnss', models.BooleanField(default=True, help_text='Ce composant est-il soumis aux cotiations CNSS?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payslip')),
                ('salary_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_items', to='payroll.salarycomponent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.UniqueConstraint(fields=('company', 'nom'), name='unique_salary_component_name_per_company'),
        ),
    ]
