# Generated by Django 6.0.6 on 2026-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.TextField(blank=True, default='', help_text='Signature en Base64 ou SVG'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('pdg', 'PDG / Direction Générale'), ('responsable_rh', 'Responsable RH'), ('admin_rh', 'Responsable RH'), ('manager', 'Manager'), ('employe', 'Employe')], default='employe', max_length=20),
        ),
    ]
