# Generated by Django 6.0.6 on 2026-07-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Préfixe court utilisé pour générer les matricules, ex:RH, IT, FIN', max_length=50),
        ),
    ]
