# Generated by Django 6.0.6 on 2026-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='matricule',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
