# Generated by Django 6.0.6 on 2026-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salaire_de_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salaire brut mensuel de base, utilisé pour générer les bulletins de paie.', max_digits=12),
        ),
    ]
