# Generated by Django 6.0.6 on 2026-07-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_salaire_de_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nombre_personnes_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
