# Generated by Django 6.0.6 on 2026-07-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_nombre_personnes_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
