# Generated by Django 6.0.6 on 2026-09-08 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_logo'),
        ('employees', '0010_employee_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(choices=[('embauche', 'Embauche'), ('stage', 'Début de stage'), ('promotion', 'Promotion'), ('poste', 'Changement de poste'), ('salaire', 'Ajustement salarial'), ('transfert', 'Transfert de département'), ('changement_contrat', 'Changement de contrat'), ('depart', 'Départ / Fin de contrat'), ('autre', 'Autre jalon')], help_text="Type d'événement de carrière", max_length=50)),
                ('old_value', models.TextField(blank=True, default='', help_text='Valeur précédente')),
                ('new_value', models.TextField(blank=True, default='', help_text='Nouvelle valeur')),
                ('contract_type', models.CharField(blank=True, default='', help_text='Type de contrat concerné', max_length=50)),
                ('change_date', models.DateField(help_text="Date de l'événement")),
                ('reason', models.TextField(blank=True, default='', help_text='Motif ou note libre')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_histories', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_career_events', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Département concerné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='employees.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Événement de carrière',
                'verbose_name_plural': 'Parcours professionnel',
                'ordering': ['change_date', 'date_creation'],
            },
        ),
    ]
