# Generated by Django 6.0.6 on 2026-09-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='field',
            field=models.CharField(choices=[('embauche', 'Embauche'), ('stage', 'Début de stage'), ('promotion', 'Promotion'), ('poste', 'Changement de poste'), ('salaire', 'Ajustement salarial'), ('transfert', 'Transfert de département'), ('changement_contrat', 'Changement de contrat'), ('depart', 'Départ / Fin de contrat'), ('recommandation', 'Recommandation managériale'), ('autre', 'Autre jalon')], help_text="Type d'événement de carrière", max_length=50),
        ),
    ]
