# Generated by Django 6.0.6 on 2026-07-06 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email_contact', models.EmailField(max_length=255, unique=True)),
                ('plan_abonnement', models.CharField(choices=[('gratuit', 'Gratuit'), ('starter', 'Starter'), ('pro', 'Pro')], default='gratuit', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
