# Generated by Django 6.0.6 on 2026-07-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='format_matricule',
            field=models.CharField(choices=[('departement', 'Préfixe département + number'), ('entreprise', 'Préfixe entreprise + number')], default='entreprise', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='prefixe_matricule',
            field=models.CharField(default='EMP', help_text="Utilisé uniquement si le format est 'entreprise'. EX:NEX", max_length=10),
        ),
    ]
