# Generated by Django 6.0.6 on 2026-09-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_format_matricule_company_prefixe_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='delai_prevenance_conge_jours',
            field=models.PositiveIntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='company',
            name='devise',
            field=models.CharField(blank=True, default='FCFA', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='heure_debut_journee',
            field=models.TimeField(blank=True, default='08:00:00', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='heure_fin_journee',
            field=models.TimeField(blank=True, default='17:30:00', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='numero_ifu',
            field=models.CharField(blank=True, help_text='Numéro IFU / SIRET / Immatriculation fiscale', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pays',
            field=models.CharField(blank=True, default='Bénin', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tolerance_retard_minutes',
            field=models.PositiveIntegerField(blank=True, default=15),
        ),
        migrations.AddField(
            model_name='company',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
