# Generated by Django 6.0.6 on 2026-09-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_adresse_company_delai_prevenance_conge_jours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.TextField(blank=True, help_text="Logo de l'entreprise (Base64 data URL ou URL d'image)", null=True),
        ),
    ]
