# Generated by Django 6.0.6 on 2026-07-07 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('jours_par_an', models.PositiveIntegerField(default=0)),
                ('couleur', models.CharField(default='#378ADD', max_length=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'nom'), name='unique_leave_type_name_per_company')],
            },
        ),
    ]
