# Generated by Django 6.0.6 on 2026-07-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leaverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='ours_utilises',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='jours_utilises',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
