# Generated by Django 6.0.6 on 2026-09-02 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_remove_leavebalance_ours_utilises_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='authorization_document',
            field=models.FileField(blank=True, null=True, upload_to='leaves/authorizations/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='authorization_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='ceo_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='ceo_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='ceo_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='ceo_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='ceo_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_leave_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_leave_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_leave_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='piece_justificative',
            field=models.FileField(blank=True, null=True, upload_to='leaves/justificatifs/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='qr_code_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='statut',
            field=models.CharField(choices=[('PENDING_MANAGER', 'En attente du Manager'), ('PENDING_HR', 'En attente RH'), ('PENDING_CEO', 'En attente du PDG'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé'), ('en_attente', 'En attente du Manager'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='PENDING_MANAGER', max_length=30),
        ),
        migrations.CreateModel(
            name='LeaveApprovalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, default='', max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_history_actions', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leaves.leaverequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
